version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clients
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/clients?schema=public
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: on-failure

volumes:
  db_data:
